### ISSUE TITLE
Debian disables ensurepip

### ISSUE THREAD

**Issue by McSinyx** [FFY00/python-build#106]
build 0.0.4 uses ensurepip to ensure pip before installing build dependencies:

https://github.com/FFY00/python-build/blob/b805ff79227d7d72057068e292ab10af6861fcb6/src/build/env.py#L169

However, CPython provided by Debian does not include this module and replaces it by a script that always return 1.  I suppose we could either:

1. Let pip be a dependency for build
2. Skip ensurepip entirely and let the execution of pip fail if it doesn't exist

**Comment by pganssle** [comment]
I am inclined to treat anything of the form "`<distro>` modifies Python so that this doesn't work" as a bug for the distro to handle, but also I think at need to drop the `ensurepip` call for other reasons anyway.

I'd prefer making `pip` a dependency (which it implicitly is anyway), or possibly just falling back to `ensurepip` if `pip` isn't present.

**Comment by FFY00** [comment]
Yes, I think this is definitely a distro bug. Replacing `ensurepip` with that payload is incorrect. If they want to patch `ensurepip` to be skipped when operating in the system Python installation, they can do that, but under no circumstance should it also be skipped in different environments.

I don't want to make pip a hard dependency for isolated builds. I think we should use pip if it is in `PATH`, otherwise bootstrap pip into a custom environment with `ensurepip`.

I think the environment where we bootstrap pip into could actually be semi-permanent and shared between all builds. This would speed up isolated builds. @pganssle @gaborbernat what do you think?

**Comment by gaborbernat** [comment]
Idealistically this is a problem for the distro, and probably solved by installing ``python3-venv`` by the user. Realistically though we could fallback to ``PATH`` pip, bundle pip, etc.

> I think the environment where we bootstrap pip into could actually be semi-permanent and shared between all builds.

I'm +1 on this. Though I do consider it to be orthogonal to the issue here.

**Comment by McSinyx** [comment]
> probably solved by installing python3-venv by the user

FYI the *ensurepip is disabled* thing is from python3-venv, and as @FFY00 said

> this is definitely a distro bug. [...] If they want to patch ensurepip to be skipped when operating in the system Python installation, they can do that, but under no circumstance should it also be skipped in different environments.

I'm happy with all solutions proposed in this thread, and until one of them is implemented, I'll stay on 0.0.3.1 just fine.  Imma take a look at Debian's bug tracker and see if there's something can be done downstream.

**Comment by FFY00** [comment]
> I'm happy with all solutions proposed in this thread, and until one of them is implemented, I'll stay on 0.0.3.1 just fine. Imma take a look at Debian's bug tracker and see if there's something can be done downstream.

You don't need to stay on 0.0.3.1, the same beahvior is still available in the new version with the `--no-isolation/-n` flag :blush:

**Comment by FFY00** [comment]
@McSinyx do you know if venv still works properly?

**Comment by McSinyx** [comment]
I've just check and 0.0.4's working alright in a venv, but I think it's because the code calling ensurepip is not reached at all:

https://github.com/FFY00/python-build/blob/3082d37183ba42c0bf60125796848b630e73a633/src/build/__main__.py#L43-L58

I might miss some part of the specification/design principal of the whole PEP 517/518 and of python-build, but it'd be really nice if I can have build isolation even if I'm already in a venv.

**Comment by FFY00** [comment]
Sorry, I wasn't clear at all! I meant to ask, if creating a venv with pip (no `--without-pip`) works. This is because we will start using venv on Python 3, which will provide pip already. If venv can create a virtual environment with a working pip, this issue is fixed on Python 3.

**Comment by gaborbernat** [comment]
```Dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3

RUN python3 -m venv env || true

RUN apt-get install -y python3-venv
RUN python3 -m venv env
```

```console
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ubuntu:latest
 ---> 9140108b62dc
Step 2/5 : RUN apt-get update && apt-get install -y python3
 ---> Using cache
 ---> 7c479d206251
Step 3/5 : RUN python3 -m venv env || true
 ---> Running in 6f2339347762
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

Removing intermediate container 6f2339347762
 ---> 4406316bac77
Step 4/5 : RUN apt-get install -y python3-venv
...
Running hooks in /etc/ca-certificates/update.d...
done.
Removing intermediate container 481833d7fd8e
 ---> 08078fca859a
Step 5/5 : RUN python3 -m venv env
 ---> Running in f096a0aaf204
Removing intermediate container f096a0aaf204
 ---> ebd54add66f5
Successfully built ebd54add66f5
```

So no, it will not work without the user install python3-venv.

**Comment by McSinyx** [comment]
As a Debian user, I'm fine with having to install `python*-venv`.  I've just taken a look at [Debian's patch](https://salsa.debian.org/cpython-team/python3/-/blob/python3.8/debian/patches/ensurepip-disabled.diff) (I know I promised to do this earlier, but my uni ate all of my time :smiley:) and it seems that the build.env.IsolatedEnvironment is not indicating enough to Debian that it's creating a virtual environment.  Modifying either `prefix` and `base_prefix` or just `real_prefix` should work around the patch.

**Comment by gaborbernat** [comment]
> Modifying either `prefix` and `base_prefix` or just `real_prefix` should work around the patch.

I don't follow how we can patch? Without ensurepip there's no way for the python to create an isolated build environment. Sure you can apply tens of patches, but you'll always miss something, as is the case with https://github.com/FFY00/python-build/issues/97. 

IMHO this project should do nothing. Debian's patching in thise case does not make sense, and is the responsibility of Debian to fix it. Or enforce its users to manually install ``python*-venv``.

**Comment by FFY00** [comment]
> As a Debian user, I'm fine with having to install `python*-venv`.

Yeah, I agree. Especially since this is not our bug.

**Comment by kitterma** [comment]
Since @doko42 is the Debian maintainer for the Python interpreters, it's really his call, but as I understand it, it's not a bug.  It's a deliberate design choice, so it would be appropriate to let us solve it.  If I recall his rationale correctly it's that pip is primarily a developer tool and it's overkill to install it on end-user systems where Python is installed because they installed something else written in Python.

**Comment by FFY00** [comment]
Right, but that completely misses the fact that it may be run in an isolated environment :confused:

**Comment by kitterma** [comment]
No.  It optimizes for the predominate case.  Installing python3-venv is a trivial one time operation if someone wants it.  Most Debian users aren't going to be doing that.

**Comment by pganssle** [comment]
Whatever, it does suck that it will increase our support burden, but we can always put in the FAQ that Debian users should not use the (deliberately) broken version of Python that Debian ships. It wouldn't be the first time.

**Comment by kitterma** [comment]
It's a lot easier to install the bits that aren't there by default than to build your own interpreter.  In any case, I'm just trying to explain the rationale.  It's @doko42's call.

**Comment by gaborbernat** [comment]
> No. It optimizes for the predominate case. Installing python3-venv is a trivial one time operation if someone wants it. Most Debian users aren't going to be doing that.

I get the idea, but removing parts of the core language still feels a bit off. Python comes with batteries included, unless you're on Debian, because then some have been removed. Most users will not need the [tar module)(https://docs.python.org/3/whatsnew/3.8.html#tarfile), but you're not removing that part, aren't you? The same logic could be applied there too:

> Installing python3-tar is a trivial one time operation if someone wants it.

**Comment by McSinyx** [comment]
> I don't follow how we can patch?

I was trying to say that somehow getting the conditional in the patch passes alright.  E.g. the following would show that build's virt env is not recognized as such:
```python
from subprocess import run
from sys import executable

from build.env import IsolatedEnvironment

PRINT_PREFIXES = """import sys

print(f"{sys.base_prefix=}")
print(f"{sys.prefix=}")
print(f"{getattr(sys, 'real_prefix', None)=}")
"""

with IsolatedEnvironment.for_current():
    run([executable, '-c', PRINT_PREFIXES])
```

since this is what I got:
```
sys.base_prefix='/usr'
sys.prefix='/usr'
getattr(sys, 'real_prefix', None)=None
```

Note that [pip uses the exact same mechanism to identify virt envs](https://github.com/pypa/pip/blob/8ce5d5abbcc5bbcb8b3bf1f364ac6540a2b60b22/src/pip/_internal/utils/virtualenv.py#L21-L44), so the problem here is not Debian's ensurepip doesn't run in virt env, but rather build creates neither a PEP-405-compliant venv (where prefix != base_prefix) nor a legacy virtualenv (which used real_prefix), and uses `pip install --prefix`.

> we can always put in the FAQ that Debian users should not use the (deliberately) broken version of Python that Debian ships.

IIRC build was originally written to be a standard python build tools for distro maintainers (exclusively to solve Arch's packaging principals).  It's unlikely excluding Debian because of its packaging principle would be a good choice were I to make the call.  Also speaking as a maintainer of a few Python packages, if I have to tell my peers to do things differently on Debian based distros, I'd rather tell them to directly build using the backends.

**Comment by gaborbernat** [comment]
> IIRC build was originally written to be a standard python build tools for distro maintainers (exclusively to solve Arch's packaging principals).

Originally. But we agreed to drop this angle once we decided to move it within PyPa. So what was originally here is irrelevant.


> I was trying to say that somehow getting the conditional in the patch passes alright. E.g. the following would show that build's virt env is not recognized as such:

I don't follow. What conditional, what patch? We're not talking here about the virtual environment of the build. We're talking here about the standard library included venv module is not functional on debian (without the ensurepip package). 

> Also speaking as a maintainer of a few Python packages, if I have to tell my peers to do things differently on Debian based distros, I'd rather tell them to directly build using the backends.

This is your choice of OS stance on the topic, so if you want to keep using it you'll need to oblige to their advice:

> Installing python3-venv is a trivial one time operation if someone wants it.

**Comment by McSinyx** [comment]
> Originally. But we agreed to drop this angle once we decided to move it within PyPa. So what was originally here is irrelevant.

I definitely missed this discussion, sorry :sweat_smile:

> What conditional, what patch?

[Debian's patch to ensurepip](https://salsa.debian.org/cpython-team/python3/-/blob/python3.8/debian/patches/ensurepip-disabled.diff) that I thought we're all referring to here, which raises error upon `sys.prefix == getattr(sys, "base_prefix", sys.prefix) or not hasattr(sys, 'real_prefix')`.  To be clear, I don't (think that any Debian user would) object to installing python3-venv, the issue here it to find at least a work-around to let python-build employs build isolation on Debian's Python.  IIUC then as of 0.0.4, python-build

* Works with --no-isolation
* Works in a venv but don't isolate build (because env.install not called in `_build_in_current_env`)
* Doesn't work outside of a virt env without --no-isolation

I'm not sure whether I somehow misread the discussion above if it was about letting python-build use venv so that Debian's Python could correctly recognize that `python3 -m ensurepip` is called in a virt env; and if that was the case, please take my apologies, as well as appreciation.

**Comment by pganssle** [comment]
This doesn't really matter for the purposes of making Debian packages, because probably Debian packagers will use the non-isolated environment mode anyway, and even if they didn't, they can set a build-time dependency on `python-venv`.

The problem is really that a lot of people use Debian and Ubuntu for some reason, and most of those people tend to use the system Python, so when they try and use the recommended tool for building python packages in the default configuration, it will be broken.

I think that as long as we detect the issue and point them to something indicating why they would probably stop using Debian's system Python, that's as good as we can do. Maybe eventually Debian will stop this near-universally reviled practice, but really it's not our bug.

**Comment by pradyunsg** [comment]
I'm not sure how I feel about adding Debian-specific code to work around things being borked due to their patches, but if that results in a nicer user experience... 🤷🏽‍♂️

**Comment by McSinyx** [comment]
I'm not sure why everyone is talking about python3-venv, but what do y'all here think about (1) build isolation is no-op if python-build is called in a virtual environment and (2) the environment created by build.env.IsolatedEnvironment does not look like a virtual environment (and thus pip is used with --prefix instead of automatically determining the install location).  Are these by design or just something that wasn't thought of?

I understand that I somehow turn the original issue into this and thus caused some confusion, so feel free to rename the issue or tell me to create a new one to reflect it.

Regarding what Debian does, I don't think there an argument from the users' side (i.e. me!) about having to install python3-venv—if anyone needs to just build and not install some packages, perse is very likely to have that package on per system anyway.

The issue is that the patched ensurepip can't not see the environment python-build provides as virtual, because [sys.base_prefix somehow doesn't point to the base/non-virtual environment] but the supposed-to-be-virtual environment, [as showed by the short script above](https://github.com/FFY00/python-build/issues/106#issuecomment-703463157).

    goto point (2) of the first paragraph

**Comment by FFY00** [comment]
I am perplexed with the Debian's position, both as a distro packager and an upstream maintainer. I now understand why so many Python devs bring their own interpreter instead of using the one the distro gave them. In my opinion, this is ridiculous, both removing `ensurepip`'s content and splitting out modules that should always be present, I think it results in awful UX.

> It's a lot easier to install the bits that aren't there by default than to build your own interpreter.

Have you considered the assumptions this is breaking and how difficult it is to debug these kind of issues?? If you know what is wrong, yes, it is trivial to install the missing bits, but the problem is not that, it's how you get there. Also, it is really not that difficult to build your own interpreter, https://github.com/pyenv/pyenv. If I was using Debian I would just definitely use my own interpreter instead of trying to deal with the brokeness that is Debian's.

So, I urge you to reconsider your position on this. Expecially on `ensurepip` which is broken and without good alternative. It seems like we are not the only ones running into this kind of issues, apparently dephell has to bring their own `ensurepip`? https://github.com/dephell/dephell_venvs/blob/5d323406128fc8e9cfd1a9c88a59b99dcf0f79ea/dephell_venvs/_ensurepip.py

Just to clarify the status quo. Right now `IsolatedEnvironment`, and by extension isolated builds (the default), are broken on Debian. With #112, on Debian isolated builds will work on Python 3 **if** the user has installed `python3-venv` and will stay broken on Python 2. Comparing this to other systems: everything is working everywhere else :neutral_face:

**Comment by McSinyx** [comment]
I'm 100% satisfied with what proposed in GH-112 and FYI [python2 is (slowly) being removed from Debian](https://wiki.debian.org/Python/2Removal) so, thanks!

**Comment by doko42** [comment]
> I am perplexed with the Debian's position, both as a distro packager and an upstream maintainer. I now understand why so many Python devs bring their own interpreter instead of using the one the distro gave them. In my opinion, this is ridiculous, both removing `ensurepip`'s content and splitting out modules that should always be present, I think it results in awful UX.

Debian has the policy that every package is built from source. I know that at least Fedora shares this requirement. I don't know about ArchLinux. You may like that policy or not, but calling this "ridiculous" seems odd. So basically you have two options for packaging:

- include the source for ensurepip in the python distro source package, and build everything from source.
- use the pip packaged by Debian to provide a pip to Debian developers and users.

The first solution is not really maintainable and would duplicate the work packaging pip for the distro (which is a different story), so to have a python3-venv package depending on pip seems the way to go.

Whether all modules should be required or not is a different story.  If you put everything into one package (apparently as ArchLinux is doing), you are required to install it's dependencies. If a source package is splitted into different binary packages, then the user has the choice to only install the required dependencies (E.g. an installation without idle and any X libraries & tools). Binary packages are the way to define the installation granularity for many Linux distributions; there might be other techniques like extracting only needed stuff for one application and only ship that, but that's not available for distributions.

**Comment by doko42** [comment]
> This doesn't really matter for the purposes of making Debian packages, because probably Debian packagers will use the non-isolated environment mode anyway, and even if they didn't, they can set a build-time dependency on `python-venv`.

yes, Debian policy requires that all build dependencies are satisfied by the Debian archive, nothing else.

> The problem is really that a lot of people use Debian and Ubuntu for some reason, and most of those people tend to use the system Python, so when they try and use the recommended tool for building python packages in the default configuration, it will be broken.

As I outlined in the last comment, Debian is using binary packages to allow for minimal installations as well. It comes down to the definition of the "default configuration".  Should that include pip? include a compiler? include build dependencies for various other third party packages?

I understand that it is *convenient* for developers of Python applications to have everything installed by default, however that is not the only community served by a Linux distribution.

> I think that as long as we detect the issue and point them to something indicating why they would probably stop using Debian's system Python, that's as good as we can do. Maybe eventually Debian will stop this near-universally reviled practice, but really it's not our bug.

I am sorry to hear your conclusion.  Forcing users and developers into a pip only install mode might be understandable from the viewpoint of a pip developer, but that's not what I am used from the rather inclusive Python community.

**Comment by doko42** [comment]
> > No. It optimizes for the predominate case. Installing python3-venv is a trivial one time operation if someone wants it. Most Debian users aren't going to be doing that.
> 
> I get the idea, but removing parts of the core language still feels a bit off. Python comes with batteries included, unless you're on Debian, because then some have been removed.

It's not removed, it's split out into a separate binary package.Calling ensurepip a part of the core language seems to be questionable, as it's source is *not* part of the core language.  Yes, batteries included, but where do you stop shipping the whole power plant?  Most users will not be aware of those splits, and developers should be able to cope with additional dependencies.

> Most users will not need the [tar module](https://docs.python.org/3/whatsnew/3.8.html#tarfile), but you're not removing that part, aren't you?

No, I wouldn't remove any modules, only splitting those out. However this comes with a burden to Linux package maintainers adding extra dependencies for their packages.  Usually this is only done for license reasons (e.g. gdbm), or heavy external dependencies (e.g. X libraries, pip stack).

**Comment by FFY00** [comment]
> Debian has the policy that every package is built from source. I know that at least Fedora shares this requirement. I don't know about ArchLinux.

Arch Linux has the very same requirement.

> So basically you have two options for packaging:
> 
>     * include the source for ensurepip in the python distro source package, and build everything from source.
>     * use the pip packaged by Debian to provide a pip to Debian developers and users.

The Debian provided pip should be used by users/developers on the system Python, not an `ensurepip` provided pip. The problem here is that we need a way to bootstrap pip into a virtual environment. Simply removing the `ensurepip` payload breaks this.

See what I said in my first reply to the issue:

> If they want to patch `ensurepip` to be skipped when operating in the system Python installation, they can do that, but under no circumstance should it also be skipped in different environments.

Please keep in mind that `ensurepip` is a Python module and can be, and is!, used in virtual environments. By removing the whole payload you are breaking this. This is what I said to consider ridiculous. So yeah, feel free to patch `ensurepip` to skip when operating on the system Python but keep the payload there usable on virtual environments.

> Whether all modules should be required or not is a different story. If you put everything into one package (apparently as ArchLinux is doing), you are required to install it's dependencies. If a source package is splitted into different binary packages, then the user has the choice to only install the required dependencies (E.g. an installation without idle and any X libraries & tools). Binary packages are the way to define the installation granularity for many Linux distributions; there might be other techniques like extracting only needed stuff for one application and only ship that, but that's not available for distributions.

What is the binary requirement of `venv`?

**Comment by doko42** [comment]
> > So basically you have two options for packaging:
> > ```
> > * include the source for ensurepip in the python distro source package, and build everything from source.
> > * use the pip packaged by Debian to provide a pip to Debian developers and users.
> > ```
> 
> The Debian provided pip should be used by users/developers on the system Python, not an `ensurepip` provided pip. The problem here is that we need a way to bootstrap pip into a virtual environment. Simply removing the `ensurepip` payload breaks this.

If ensurepip cannot be shipped because it is not built in any binary package in the distro, how do you want to provide it for virtual environments?

> See what I said in my first reply to the issue:
> 
> > If they want to patch `ensurepip` to be skipped when operating in the system Python installation, they can do that, but under no circumstance should it also be skipped in different environments.
> 
> Please keep in mind that `ensurepip` is a Python module and can be, and is(!), used in virtual environments. By removing the whole payload you are breaking this. This is what I said to consider ridiculous. So yeah, feel free to patch `ensurepip` to skip _when operating on the system Python_ but keep the payload there usable on virtual environments.

sorry, that's something I don't understand. Where do you get this payload from?
Looking at https://www.archlinux.org/packages/extra/x86_64/python/
you are shipping the wheels/binaries included in CPython, so *not* building from source.  This may be allowed by ArchLinux policy, but I can't do that for Debian.

**Comment by pradyunsg** [comment]
> Should that include pip?

I'd argue yes, given that the python.org builds of CPython does include pip and basically every other distro does as well. :)

> No, I wouldn't remove any modules, only splitting those out.

The point was if "most people don't need X" is the line of reasoning to split out a component (in this case `venv`), *many* other parts of the Python standard library satisfy that criterion (in this example `tar`).

**Comment by FFY00** [comment]
Just to clarify a few things, I consider Debian's approach to split modules into different packages because of binary dependencies valid and perfectly reasonable. But I think one should not take such decisions lightly, we should always keep in mind *how* it affects users. At least that is what I try to do, we need to draw a balance between 

> If ensurepip cannot be shipped because it is not built in any binary package in the distro, how do you want to provide it for virtual environments?

But you can build the wheels from source and put them there.

> sorry, that's something I don't understand. Where do you get this payload from?
> Looking at [archlinux.org/packages/extra/x86_64/python](https://www.archlinux.org/packages/extra/x86_64/python/)
> you are shipping the wheels/binaries included in CPython, so _not_ building from source. This may be allowed by ArchLinux policy, but I can't do that for Debian.

I'd argue it is agaisnt Arch Linux policy but since they are pure Python, it's a grey area. I have opened a bug report suggesting to build the wheels from source.

**Comment by FFY00** [comment]
Just to clarify a few things, I consider Debian's approach to split modules into different packages because of binary dependencies valid and perfectly reasonable. But I think one should not take such decisions lightly, we should always keep in mind *how* it affects users. At least that is what I try to do, we need to draw a balance. I know it can be difficult to understand exactly how things affect users, but it is extremely important since it's their lives I will be impacting.

In this case, I don't really understand the need to split out `venv`, `distutils`, etc. which have no binary dependency. Could you elaborate here? :blush:

**Comment by pganssle** [comment]
I understand the merits of what Debian is doing, but it makes it impossible for us to provide a consistent user experience because there's no way to declare that `python-build` depends on `venv`. Users who get `python-build` via `apt-get` or whatever won't have this problem.

I assume that @doko42 is aware that this is a consistent source of bugs for end users (almost certainly causing more problems than patching the default `pip` to default to `--require-virtualenv` would cause) and that this affects upstream packages as it causes users to come to our packages complaining that it doesn't work because Debian provides something other than a full Python installation and calls it "Python". I assume that this has gone into their cost-benefit analysis and at the end of the day provoking enmity with upstream maintainers is apparently worth the perceived benefits. That is fine (though I'd be perfectly happy if the PSF asked Debian to stop calling their modified distribution "Python", since that is basically the core of the issue).

At the end of the day, I think all the maintainers here are in agreement that this is not our problem. I suggest that we just go ahead and try to detect the situation and raise an exception pointing to a FAQ.

Optionally, we can probably explicitly mention that we don't support using the default Debian/Ubuntu distribution, even in a virtual environment, and that people should reproduce their bugs using `pyenv` or using a different OS before reporting them. I imagine people will pay zero attention to such a declaration, but at least we can link to it.

**Comment by doko42** [comment]
> Just to clarify a few things, I consider Debian's approach to split modules into different packages because of binary dependencies valid and perfectly reasonable. But I think one should not take such decisions lightly, we should always keep in mind _how_ it affects users. At least that is what I try to do, we need to draw a balance. I know it can be difficult to understand exactly how things affect users, but it is extremely important since it's their lives I will be impacting.

thanks for the balanced view. I appreciate it. I want to question your use of the word "users", because most users won't see the splitting at all and as such not as a problem, installing packages from the distro archive.  I would rather say that a large amount of users doesn't care, and can live with was is provided, but a vocal group of developers is a bigger issue than it is. 

> In this case, I don't really understand the need to split out `venv`, `distutils`, etc. which have no binary dependency. Could you elaborate here?

I think we don't need to talk about distutils anymore, it will be deprecated and removed.  The two reasons for splitting out venv are

- size: the bundled wheels, and wheels which are devendored for Debian have a substantial size, and are not needed in most non-development 

- Don't install what you don't need. Adding more in a default install usually increases any attack vector, although you might want to argue that the Python interpreter is usually enough to get done what you want.

**Comment by doko42** [comment]
@pganssle, I'm disappointed about your way to polemicise and threaten. If that's the only way to go, please go ahead. Just state that you are only interested in supporting pure pip installations, as you already did at the distutils/setuptools sprint at PyCon US 2019.

If the only thing needed is having python-build a dependency on python-venv, then let's provide an egg for that module and you can depend on that. If that needs a PEP, then lets write one. If anything else is needed, then lets work on that.

**Comment by gaborbernat** [comment]
Hey, I personally have no issues with debian splitting out python-venv. I find it unfortunate for ease of onboarding new users who develop on Debian, but that's it. This project must depend on venv, and there's no way around that.

That being said, we already print out the error message Debian provides when invoking ensurepip, so I think that's enough hint of the end users how to solve it. I don't think there's need for anything more. Just a caveat for end-users that who wants to use ``python-build`` instaleld from PyPi (not apt) will need to install the ``python3-venv`` (as it provides ensurepip venv uses, and we use venv) package to make it work.

Users who develop for Debian will need to follow this, and this inconveniance is a barrier of entry that as @doko42 put it is there to help the majority of users of the OS, rather than favour ease of development in case of few. With that I consider this issue as can be closed.

**Comment by pganssle** [comment]
> That being said, we already print out the error message Debian provides when invoking ensurepip, so I think that's enough hint for the end users how to solve it. I don't think there's need for anything more. Just a caveat for end-users who install
> `python-build` from PyPi (instead of a potential future python3-build package) will need to install the `python3-venv` to make it work (as it provides ensurepip venv uses, and we use venv).

Won't people see somewhat cryptic "no module named `venv`" when they run this on Debian without installing `python3-venv`, and then come complaining to us?

Even though it is emphatically not our problem, it seems to me it would be better to do something like this:

```python
try:
    import venv
except ImportError:
    raise ImportError("The module venv is not found. This usually happens if you are using a patched or otherwised modified version of Python. See python-build.readthedocs.io/faq#why-doesnt-this-work-on-debian for more details.")
```

**Comment by gaborbernat** [comment]
> Won't people see somewhat cryptic "no module named `venv`" when they run this on Debian without installing `python3-venv`, and then come complaining to us?

No because ``python-venv`` actually does not contain the venv module only the ensurepip one. 

The error message with latest version is very descriptive:

```
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/env/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

I consider it good enough. If it needs improved should be done on the Debian side.

**Comment by doko42** [comment]
this won't help. the venv module *is* part of the install, when you install "python3".

**Comment by pganssle** [comment]
Ah, sounds good to me, let's close this issue and we can re-examine it if we get too many users complaining about Debian's broken package.
