### ISSUE TITLE
consider using black

### ISSUE THREAD

**Issue by gaborbernat** [FFY00/python-build#19]
Would you be ok with using the black formatter on the codebase?

**Comment by FFY00** [comment]
I am not a fan of black, but if the codebase grows large enough that maintaining a consistent code style becomes a burden, or contributors feel better using it, I am okay with letting that go.

**Comment by pganssle** [comment]
I'm +1 on using `black` or any other code formatter from as close to the beginning as possible. If you wait until the code-base stabilizes, you'll probably end up with the `git blame` for nearly every line being "Fix black" or whatever (even though you can add a thing that ignores certain commits in blame, I don't think it works on github, which is the only place I ever use `blame`).

Ever since I've started using code formatters, I've really resented having to pay attention to manually formatting my code, like... at all. If we adopted `black` right now with no options, this is the diff:

```
$ git diff --numstat
15      15      docs/source/conf.py
24      18      noxfile.py
18      25      setup.py
1       1       tests/__init__.py
43      42      tests/test_main.py
63      57      tests/test_projectbuilder.py
```

With `--skip-string-normalization`, it's:

```
$ git diff --numstat
7       1       noxfile.py
3       0       pyproject.toml
5       12      setup.py
14      13      tests/test_main.py
9       3       tests/test_projectbuilder.py
```

With `--line-length=80`, it's:

```
$ git diff --numstat
17      15      docs/source/conf.py
24      18      noxfile.py
3       0       pyproject.toml
18      25      setup.py
1       1       tests/__init__.py
62      43      tests/test_main.py
77      61      tests/test_projectbuilder.py
```

With `--skip-string-normalization` and `--line-length=80`, it's:

```
$ git diff --numstat
3       1       docs/source/conf.py
7       1       noxfile.py
5       0       pyproject.toml
5       12      setup.py
34      15      tests/test_main.py
24      8       tests/test_projectbuilder.py
```

Usually I use `black` with `--line-length=80`, but I don't feel strongly about the line length issue. I don't love the fact that it's `--skip-string-normalization` instead of something like `--use-single-quotes`, because I've grown into the habit of always using double quotes in my code now, but if we're worried about the effect on `git blame`, if we can configure `flake8` or `pylint` or something to enforce black's double-quotes rule only on changed portions of the code base, I think it wouldn't be the worst thing to do a gradual migration to double quotes over time.

**Comment by FFY00** [comment]
I think `line-length=80` is a bit antiquated, I usually use 127, which is the size of the Github code viewer/editor.

My biggest pet peeve is double quotes, it takes me an extra keypress to type them, and I need to use them so often this becomes annoying. I guess black can handle them for me, but then my OCD just spikes up when reading the code. The biggest thing I have against black is exactly the lack of `--use-single-quotes`, `--skip-string-normalization` is not the same :confused:.

Fun fact, CPython seems to prefer single quotes:
```
>>> "oh"
'oh'
```

If you want a code formatter, may I suggest yapf?

I will not block the adoption of black, but I wanted to state my position on it.

**Comment by gaborbernat** [comment]
The whole point of the code formatter is that you type whatever you want. Before commit call and transforms to the standard. I'd strongly prefer black.

**Comment by FFY00** [comment]
Sorry, misclick.

I understand how it is supposed to be used.

This is my problem:
> I guess black can handle them for me, but then my OCD just spikes up when reading the code.

Anyway, I will not block the adoption of black. If you two feel strongly about it then just go ahead.
