### ISSUE TITLE
use pre-commit from remotes

### ISSUE THREAD

**Issue by gaborbernat** [FFY00/python-build#38]
pre-commit at the moment tries to piggyback on the local environments, see https://github.com/FFY00/python-build/blob/master/.pre-commit-config.yaml can we instead use the better supported/easier to upgrade, more declarative method? As in https://github.com/pypa/virtualenv/blob/master/.pre-commit-config.yaml#L2

**Comment by FFY00** [comment]
I think we should make pre-commit run nox instead and maintain the test suite there. However, nox is super slow and I don't want to wait 48s every time I make a commit. I think we should consider using tox, do you want to do the honors?

**Comment by gaborbernat** [comment]
> I think we should make pre-commit run nox instead and maintain the test suite there.

What do you mean here?

> I think we should consider using tox, do you want to do the honors?

Sure, but heads up. tox might be somehow faster, tox 4 ETA Q4 would be probably a lot faster. That being said most overhead should occur only on first overhead.

**Comment by FFY00** [comment]
> What do you mean here?

Agh, nevermind. I forgot the pre-commit has special handling for the modified files and wants to pass them to the tools to speed up things.

Feel free to open a PR with the changes you propose.

**Comment by pganssle** [comment]
Is there a way to tell pre-commit not to run the tests, because if not I really don't think running the test suite should be part of pre-commit (that is done with `nox` / `tox` or CI). I really only use it for linting and things of that nature, and rely on CI and/or local invocations of `tox` / `nox`.

I imagine I would simply not install the pre-commit hooks if they were going to add more than 1-2 seconds to the time it takes to commit.

**Comment by FFY00** [comment]
Sure, we can just remove the pytest hooks.

**Comment by gaborbernat** [comment]
I'll put in a PR to migrate to tox, and pre-commit to checks only then?

**Comment by FFY00** [comment]
Yes, submit one PR for each.

**Comment by FFY00** [comment]
Solved in #47.
